### PR TITLE
Add Multi Task Options Support

### PR DESCRIPTION
**Pull request by kmgilbert100**
- Add multi task options support (helps with verifying multiple dir at once)
- Bumped version to 0.3.3

### CODE REVIEW

**Comment by stevewillard** [comment]
LGTM

**Comment by kmgilbert100** [comment]
Can you publish this to npm as well trying to install 0.3.3 :+1:

**Comment by stevewillard** [comment]
I made some quick style and doc changes, and just published to NPM. Give it a try. Looks like you'll need to include a target as part of the Gruntfile now, since it's a multitask

**Comment by kmgilbert100** [comment]
Meh not picking it up yet darn npm repo .. just install from github till that updates.. tried cache clean too

**Comment by msimerson** [comment]
> Looks like you'll need to include a target as part of the Gruntfile now, since it's a multitask

I just got bit by that. Might be a good to drop a an `UPGRADE` section in the README noting that the syntax used in older Gruntfiles (without `target:`) is broken.

**Pull request merged**
